version: '3.8'

services:
  new-api:
    image: thelazy/new-api:latest
    container_name: new-api
    restart: always
    command: --log-dir /app/logs
    ports:
      - "127.0.0.1:3721:3000"
    volumes:
      - ./data:/data
      - ./logs:/app/logs
    environment:
      - SQL_DSN=root:123456@tcp(mysql:3306)/new-api
      - LOG_SQL_DSN=root:123456@tcp(mysql:3306)/new-api-logs
      - REDIS_CONN_STRING=redis://redis
      - TZ=Asia/Shanghai
      - ERROR_LOG_ENABLED=true
      - GLOBAL_API_RATE_LIMIT=1800
      - GLOBAL_WEB_RATE_LIMIT=600
      - STREAMING_TIMEOUT=360
      - MAX_FILE_DOWNLOAD_MB=50
      - GENERATE_DEFAULT_TOKEN=true
    depends_on:
      - redis
      - mysql
    networks:
      - new-api-network
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O - http://localhost:3721/api/status | grep -o '\"success\":\\s*true' | awk -F: '{print $$2}'"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:latest
    container_name: new-api-redis
    restart: always
    networks:
      - new-api-network

  mysql:
    image: mysql:8.2
    container_name: new-api-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "127.0.0.1:3306:3306"
    networks:
      - new-api-network

volumes:
  mysql_data:

networks:
  new-api-network:
    driver: bridge